package com.adv.ilook.model.util.service.appservice

enum class MainServiceActions {
                              INIT_SERVICE,
   START_SERVICE,SETUP_VIEWS,END_CALL,SWITCH_CAMERA,TOGGLE_AUDIO,TOGGLE_VIDEO,TOGGLE_AUDIO_DEVICE,
   TOGGLE_SCREEN_SHARE,STOP_SERVICE,START_WIFI_SCAN,HANDLE_PROJECTION


}